# Official Python Docker Image
FROM dev.registry.apps.devjones.com/python:3.11-slim

# Set working directory 
WORKDIR /app

# Copy requirements first to leverage Docker Cache
COPY requirements.txt .

# Install Dependencies 
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose Port 8085 for FastApi
EXPOSE 8085

# Run the app with Uvicorn
CMD ["uvicorn", "WeatherForecastService:app", "--host", "0.0.0.0", "--port", "8085"]

### Uncomment below to launch the container for debugging
# CMD ["/bin/bash"]